#Wed Feb 03 15:37:30 ICT 2021
algorithms=u01.01.cosine, u02.02.pearson_constrained, u03.04.dice, u04.02.msdj, u05.02.nhsm, u08.01.smd, u09.01.smd2, u09.13.02.smd2xta, u09.14.02.smd2xcpc, u10.02.taj

trainingsets=datasets/movielens/hdp_rating1.base#snapshot_parser#file, datasets/movielens/hdp_rating2.base#snapshot_parser#file, datasets/movielens/hdp_rating3.base#snapshot_parser#file, datasets/movielens/hdp_rating4.base#snapshot_parser#file, datasets/movielens/hdp_rating5.base#snapshot_parser#file

testingsets=datasets/movielens/hdp_rating1.test#snapshot_parser#file, datasets/movielens/hdp_rating2.test#snapshot_parser#file, datasets/movielens/hdp_rating3.test#snapshot_parser#file, datasets/movielens/hdp_rating4.test#snapshot_parser#file, datasets/movielens/hdp_rating5.test#snapshot_parser#file
